---
jobs:
  merge:
    if: contains(github.event.pull_request.labels.*.name, 'automerge')
    runs-on: ubuntu-latest
    steps:
    - id: metadata
      name: Dependabot metadata
      uses: dependabot/fetch-metadata@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        PR_URL: ${{github.event.pull_request.html_url}}
      name: Approve a Pull Request
      run: gh pr review --approve "$PR_URL"
name: Auto Merge Pull Request
on:
  pull_request:
    branches:
    - development
permissions:
  pull-requests: write
