---
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: "0"
    - name: Common Templates
      uses: BetaHuhn/repo-file-sync-action@v1
      with:
        ASSIGNEES: andrewcole
        COMMIT_BODY: "Synced common templates #patch"
        CONFIG_PATH: templates/common.yaml
        GH_PAT: ${{ secrets.PAT }}
        PR_LABELS: automerge
    - name: Docker Templates
      uses: BetaHuhn/repo-file-sync-action@v1
      with:
        ASSIGNEES: andrewcole
        COMMIT_BODY: "Synced docker templates #patch"
        CONFIG_PATH: templates/docker.yaml
        GH_PAT: ${{ secrets.PAT }}
        PR_LABELS: automerge
name: Sync Templates
on:
  push:
    branches:
    - development
