---
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: "0"
    - name: Run GitHub File Sync
      uses: BetaHuhn/repo-file-sync-action@v1
      with:
        ASSIGNEES: andrewcole
        CONFIG_PATH: .github/sync.yaml
        GH_PAT: ${{ secrets.GH_PAT }}
name: Synchronise Files
on:
  push:
    branches:
    - development
