---
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: "0"
    - name: Run GitHub File Sync
      uses: BetaHuhn/repo-file-sync-action@v1
      with:
        ASSIGNEES: andrewcole
        CONFIG_PATH: templates/docker.yaml
        GH_PAT: ${{ secrets.PAT }}
        PR_LABELS: automerge
name: Sync Docker Template
on:
  push:
    branches:
    - development
